apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: custom-jenkins
  name: custom-jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: custom-jenkins
    spec:
      containers:
        - name: custom-jenkins
          image: 172.30.1.1:5000/myproject/custom-jenkins@sha256:a72144d5412a13ecf9c54baef4750406b6c88ac56f57410a481ca9cd69047ca6
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
      imagePullPolicy: Always
