apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: custom-jenkins
  name: custom-jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: custom-jenkins
    spec:
      containers:
        - name: custom-jenkins
          image: 172.30.1.1:5000/myproject/custom-jenkins
          env:
            - name: "JENKINS_PASSWORD"
              value: "admin"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
      imagePullPolicy: Always
    triggers:
      - type: "ImageChange"
        imageChangeParams:
          automatic: true
          containerNames:
            - "custom-jenkins"
          from:
            kind: "ImageStreamTag"
            name: "custom-jenkins-build:latest"
    strategy:
      type: "Rolling"
