apiVersion: v1
kind: Service
metadata:
  labels:
    app: custom-jenkins
  name: custom-jenkins
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: ui
    - port: 8081
      protocol: TCP
      targetPort: 8081
      name: jnlp
  selector:
    app: custom-jenkins
  type: LoadBalancer
