---
apiVersion: v1
kind: BuildConfig
metadata:
  name: custom-jenkins-build
spec:
  triggers:
    - type: "git"
      git:
        uri: https://github.com/JGuzman4/custom-jenkins
  source:                       
    git:
      uri: https://github.com/JGuzman4/custom-jenkins
      ref: "master"
    type: Git
  strategy:                     
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins:latest
        namespace: openshift
    type: Source
  output:                       
    to:
      kind: ImageStreamTag
      name: custom-jenkins:latest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: custom-jenkins
  name: custom-jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: custom-jenkins
    spec:
      serviceAccountName: jenkins
      containers:
        - name: custom-jenkins
          image: 172.30.1.1:5000/myproject/custom-jenkins
          env:
            - name: "JENKINS_PASSWORD"
              value: "admin"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
      imagePullPolicy: Always
    triggers:
      - type: "ImageChange"
        imageChangeParams:
          automatic: true
          containerNames:
            - "custom-jenkins"
          from:
            kind: "ImageStreamTag"
            name: "custom-jenkins-build:latest"
    strategy:
      type: "Rolling"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: custom-jenkins
  name: custom-jenkins
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: ui
    - port: 8081
      protocol: TCP
      targetPort: 8081
      name: jnlp
  selector:
    app: custom-jenkins
  type: LoadBalancer
